In [1]:
import numpy as np
import pandas as pd
import sklearn
import xgboost as xgb

In [2]:
data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")

In [3]:
Y_train = pd.read_csv("train.csv", usecols = ['Property_A','Property_B','Property_C','Property_D','Property_E','Property_F']) 

In [4]:
X_train = data.drop(['Property_A','Property_B','Property_C','Property_D','Property_E','Property_F'],axis=1)

In [ ]:
X_test = test_data
X_train1 = pd.read_csv("train.csv", sep=',',usecols = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P'])

In [ ]:

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train ,Y_train)

In [7]:
from sklearn.ensemble import RandomForestRegressor 
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train,Y_train)

RandomForestRegressor(random_state=42)

In [8]:
n_estimators = [int(x) for x in np.linspace(start = 80, stop = 200, num = 5)]
max_features = ['sqrt']
min_samples_split = [2, 5, 10]

In [9]:
search_space1 = {
    "n_estimators" : n_estimators,
    "max_depth" : [3,6,9],
    "max_features" : max_features,
    "min_samples_split" : [2, 5, 10]
}

In [10]:
from sklearn.model_selection import GridSearchCV
GS = GridSearchCV(estimator = model, param_grid = search_space1, scoring = 'neg_root_mean_squared_error',
                  refit='neg_root_mean_squared_error', cv =5, error_score='raise')
GS.fit(X_train, Y_train)

GridSearchCV(cv=5, error_score='raise',
             estimator=RandomForestRegressor(random_state=42),
             param_grid={'max_depth': [3, 6, 9], 'max_features': ['sqrt'],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [80, 110, 140, 170, 200]},
             refit='neg_root_mean_squared_error',
             scoring='neg_root_mean_squared_error')

In [11]:
print(GS.best_estimator_)

RandomForestRegressor(max_depth=6, max_features='sqrt', n_estimators=170,
                      random_state=42)


In [12]:
print(GS.best_params_)

{'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 2, 'n_estimators': 170}


In [13]:
print(GS.best_score_)

-5.045896580187571


In [14]:
predictions_rfr = model.predict(X_test)

In [16]:
pred_rfr = pd.DataFrame(predictions_rfr, columns =['Property_A','Property_B','Property_C','Property_D','Property_E','Property_F'])

In [17]:
pred_rfr

Property_A  Property_B  Property_C  Property_D  Property_E  Property_F
0        5.5475    0.687726     1.51710       51.14       18.61       30.25
1        5.5762    0.352670     1.49604       50.65       18.39       30.96
2        5.5057    0.458774     1.51008       51.29       18.73       29.98
3        5.4534    0.440258     1.50033       51.93       21.03       27.04
4        5.5187    0.518715     1.51944       51.68       17.55       30.77
..          ...         ...         ...         ...         ...         ...
96       5.9456    1.206699     1.65087       57.74       15.90       26.36
97       5.9820    1.343781     1.63137       58.19       16.02       25.79
98       5.7530    1.235054     1.60797       58.12       16.27       25.61
99       5.9329    1.276444     1.62981       58.50       15.95       25.55
100      6.0664    1.399840     1.68168       58.73       15.72       25.55

[101 rows x 6 columns]

In [93]:
df

Property_A  Property_B  Property_C  Property_D  Property_E  Property_F
0      5.467231    2.566655    1.322072   49.847332   18.426689   32.188152
1      5.411782    2.415261    1.478026   50.916985   17.731388   30.405451
2      5.515411    2.650956    1.401289   51.173267   18.573755   29.110146
3      5.160808    2.214494    1.814724   52.851273   17.854364   24.048826
4      5.315109    2.355272    1.460235   48.922558   20.024387   27.174974
..          ...         ...         ...         ...         ...         ...
96     6.545962    0.877932    1.574861   55.987282   16.704647   24.175474
97     6.730536    0.550399    1.484533   56.192520   17.213037   25.055128
98     6.028537    0.925557    1.660412   59.664780   16.913584   21.351187
99     6.469428    0.673328    1.545934   58.186539   15.988671   23.491127
100    6.472768    0.595422    1.546867   56.867638   15.786521   22.820282

[101 rows x 6 columns]

In [18]:
pred_rfr_sum = pred_rfr.sum(axis='columns')

In [19]:
pred_rfr_sum

0      107.752326
1      107.424910
2      107.474554
3      107.393988
4      107.556855
          ...    
96     108.803169
97     108.957151
98     108.596024
99     108.839154
100    109.147920
Length: 101, dtype: float64

In [91]:
pred_sum_xg

0      109.818130
1      108.358894
2      108.424820
3      103.944489
4      105.252533
          ...    
96     105.866165
97     107.226158
98     106.544060
99     106.355026
100    104.089500
Length: 101, dtype: float32

In [ ]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(Y_test, predictions_rfr))
print("RMSE: %f" % (rmse))

In [20]:
model2 = xgb.XGBRegressor(tree_method="hist", device="cuda:1")
model2.fit(X_train,Y_train)

C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\core.py:160: UserWarning: [22:27:42] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-07f6e447eee219473-1\xgboost\xgboost-ci-windows\src\context.cc:44: No visible GPU is found, setting device to CPU.
  warnings.warn(smsg, UserWarning)


XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device='cuda:1', early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [21]:
search_space = {
    "n_estimators" : [100],
    "max_depth" : [3,6,9],
    "learning_rate" : [0.01,0.1],
    "max_features" : ['sqrt']
}

In [22]:
sklearn.metrics.get_scorer_names()

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'max_error',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_root_mean_squared_error',
 'normalized_mutual_info_score',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',
 'roc_auc',
 'roc_auc_ovo',
 'roc_auc_ovo_weighted',
 'roc_auc_

In [23]:
from sklearn.model_selection import GridSearchCV
GS = GridSearchCV(estimator = model2, param_grid = search_space, scoring = 'neg_root_mean_squared_error',
                  refit='neg_root_mean_squared_error', cv =5,error_score='raise')
GS.fit(X_train, Y_train)

C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\core.py:160: UserWarning: [22:33:07] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-07f6e447eee219473-1\xgboost\xgboost-ci-windows\src\context.cc:44: No visible GPU is found, setting device to CPU.
  warnings.warn(smsg, UserWarning)
C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\core.py:160: UserWarning: [22:33:07] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-07f6e447eee219473-1\xgboost\xgboost-ci-windows\src\learner.cc:742: 
Parameters: { "max_features" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\core.py:160: UserWarning: [22:33:23] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-07f6e447eee219473-1\xgboost\xgboost-ci-windows\src\context.cc:44: No visible GPU is found, setting device to CPU.
  warn

C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\core.py:160: UserWarning: [22:40:58] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-07f6e447eee219473-1\xgboost\xgboost-ci-windows\src\context.cc:44: No visible GPU is found, setting device to CPU.
  warnings.warn(smsg, UserWarning)
C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\core.py:160: UserWarning: [22:40:58] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-07f6e447eee219473-1\xgboost\xgboost-ci-windows\src\learner.cc:742: 
Parameters: { "max_features" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\core.py:160: UserWarning: [22:42:12] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-07f6e447eee219473-1\xgboost\xgboost-ci-windows\src\context.cc:44: No visible GPU is found, setting device to CPU.
  warn

C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\core.py:160: UserWarning: [22:54:01] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-07f6e447eee219473-1\xgboost\xgboost-ci-windows\src\context.cc:44: No visible GPU is found, setting device to CPU.
  warnings.warn(smsg, UserWarning)
C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\core.py:160: UserWarning: [22:54:01] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-07f6e447eee219473-1\xgboost\xgboost-ci-windows\src\learner.cc:742: 
Parameters: { "max_features" } are not used.

  warnings.warn(smsg, UserWarning)
C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\core.py:160: UserWarning: [22:55:36] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-07f6e447eee219473-1\xgboost\xgboost-ci-windows\src\context.cc:44: No visible GPU is found, setting device to CPU.
  warn

GridSearchCV(cv=5, error_score='raise',
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device='cuda:1',
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, gamma=None,
                                    grow_policy=None, importance_type=None,
                                    interaction_constraints=N...
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None,
                                    random_state=None, ...),
             param_grid={'learning_rate': [0.01, 0.1], 'max_depth': [3, 6, 9],
                         'max_features': ['sqrt'], 'n_estimators': [100]},
             refit='neg_root_mean_squared_error',
             scoring='neg_root_mean_squared_error')

In [24]:
print(GS.best_estimator_)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device='cuda:1', early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=3, max_features='sqrt',
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)


In [25]:
print(GS.best_params_)

{'learning_rate': 0.1, 'max_depth': 3, 'max_features': 'sqrt', 'n_estimators': 100}


In [26]:
print(GS.best_score_)

-3.9535096338504787


In [27]:
predictions_xg = GS.best_estimator_.predict(X_test)

In [55]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(Y_test, predictions_xg))
print("RMSE: %f" % (rmse))

ValueError: Found input variables with inconsistent numbers of samples: [50, 101]

In [30]:
from sklearn.tree import DecisionTreeRegressor
model3 = DecisionTreeRegressor(random_state=42)
model3.fit(X_train,Y_train)

DecisionTreeRegressor(random_state=42)

In [31]:
predictions_dt = model3.predict(X_test)

In [16]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(Y_test, predictions_dt))
print("RMSE: %f" % (rmse))

RMSE: 3.067665


In [28]:
predictions_rfr

array([[ 5.5475    ,  0.6877258 ,  1.5171    , 51.14      , 18.61      ,
        30.25      ],
       [ 5.5762    ,  0.35266982,  1.49604   , 50.65      , 18.39      ,
        30.96      ],
       [ 5.5057    ,  0.45877439,  1.51008   , 51.29      , 18.73      ,
        29.98      ],
       [ 5.4534    ,  0.44025769,  1.50033   , 51.93      , 21.03      ,
        27.04      ],
       [ 5.5187    ,  0.51871501,  1.51944   , 51.68      , 17.55      ,
        30.77      ],
       [ 5.6174    ,  0.54464146,  1.49097   , 51.65      , 19.14      ,
        29.21      ],
       [ 5.6724    ,  0.42270674,  1.48863   , 49.78      , 17.48      ,
        32.74      ],
       [ 5.5658    ,  0.53608925,  1.51359   , 50.85      , 17.92      ,
        31.23      ],
       [ 5.5699    ,  0.48345361,  1.52451   , 50.49      , 18.24      ,
        31.27      ],
       [ 5.5749    ,  0.5962379 ,  1.51671   , 52.06      , 18.86      ,
        29.08      ],
       [ 5.5897    ,  0.44884577,  1.51086   , 49.

In [29]:
predictions_xg

array([[ 5.5099125 ,  1.9639562 ,  1.3562975 , 49.5994    , 17.927813  ,
        31.992481  ],
       [ 5.3616533 ,  2.2986925 ,  1.5467649 , 50.68023   , 18.397568  ,
        31.392607  ],
       [ 5.361255  ,  2.3098333 ,  1.5309938 , 50.97646   , 18.30525   ,
        29.719116  ],
       [ 5.300845  ,  2.0202131 ,  2.1562626 , 52.459522  , 17.151808  ,
        24.199966  ],
       [ 5.2613964 ,  2.5939178 ,  1.482065  , 49.689247  , 19.343454  ,
        28.194118  ],
       [ 5.4908066 ,  1.7994878 ,  1.4636014 , 50.466736  , 19.84799   ,
        32.069393  ],
       [ 5.65997   ,  2.3305037 ,  1.6125469 , 49.246193  , 16.682728  ,
        34.647606  ],
       [ 5.321507  ,  2.0592868 ,  1.619111  , 49.63705   , 16.396042  ,
        31.59309   ],
       [ 5.3823256 ,  1.2816418 ,  1.5338306 , 49.326458  , 17.977262  ,
        32.522614  ],
       [ 5.4427185 ,  2.8240626 ,  1.5952921 , 51.72642   , 18.299158  ,
        32.54201   ],
       [ 5.5770545 ,  2.1134534 ,  1.6390815 , 48.

In [68]:
predictions_dt

array([[ 5.43    ,  0.28971 ,  1.443   , 46.      , 14.      , 40.      ],
       [ 5.36    ,  1.06314 ,  1.365   , 54.      , 21.      , 25.      ],
       [ 5.46    ,  0.104052,  1.521   , 49.      , 20.      , 31.      ],
       [ 5.36    ,  1.06314 ,  1.365   , 54.      , 21.      , 25.      ],
       [ 5.19    ,  0.175305,  1.677   , 50.      , 15.      , 35.      ],
       [ 5.34    ,  0.22098 ,  1.638   , 48.      , 22.      , 30.      ],
       [ 5.21    ,  0.247863,  1.794   , 45.      , 17.      , 38.      ],
       [ 5.94    ,  0.21141 ,  1.443   , 50.      , 25.      , 25.      ],
       [ 5.99    ,  0.115797,  1.638   , 49.      , 19.      , 32.      ],
       [ 6.15    ,  0.30798 ,  1.17    , 55.      , 20.      , 25.      ],
       [ 5.17    ,  0.198882,  1.521   , 49.      , 16.      , 35.      ],
       [ 5.17    ,  0.198882,  1.521   , 49.      , 16.      , 35.      ],
       [ 5.17    ,  0.198882,  1.521   , 49.      , 16.      , 35.      ],
       [ 5.17    ,  0.198

In [33]:
df = pd.DataFrame(predictions_xg, columns =['Property_A','Property_B','Property_C','Property_D','Property_E','Property_F'])

In [34]:
df.head()

Property_A  Property_B  Property_C  Property_D  Property_E  Property_F
0    5.509912    1.963956    1.356297   49.599400   17.927813   31.992481
1    5.361653    2.298692    1.546765   50.680229   18.397568   31.392607
2    5.361255    2.309833    1.530994   50.976460   18.305250   29.719116
3    5.300845    2.020213    2.156263   52.459522   17.151808   24.199966
4    5.261396    2.593918    1.482065   49.689247   19.343454   28.194118

In [35]:
pred_sum_xg = df.sum(axis='columns')

In [90]:
pred_sum_xg = to

0      109.818130
1      108.358894
2      108.424820
3      103.944489
4      105.252533
          ...    
96     105.866165
97     107.226158
98     106.544060
99     106.355026
100    104.089500
Length: 101, dtype: float32

In [36]:
pred_rfr_sum.to_csv('submission1.csv')

In [40]:
import catboost as cb

In [38]:
model = cb.CatBoostRegressor(loss_function='MultiRMSE')

In [39]:
train_dataset = cb.Pool(X_train, Y_train)

In [ ]:
grid = {'iterations': [100],
        'learning_rate': [0.1],
        'depth': [ 4, 6],
        'l2_leaf_reg': [ 0.5, 1]}
model.grid_search(grid, train_dataset)

In [42]:
pred_cat = model.predict(X_test)

In [43]:
pred_cat

array([[ 5.59761254,  1.25276219,  1.54828236, 49.94128513, 19.2805988 ,
        30.77846675],
       [ 5.5434028 ,  0.78213616,  1.53274992, 51.42277822, 18.84976752,
        29.72776863],
       [ 5.6019812 ,  1.06970715,  1.5369472 , 52.9860121 , 18.68867648,
        28.32508973],
       [ 5.42032733,  0.60690358,  1.50315907, 53.68650822, 20.53769664,
        25.7756889 ],
       [ 5.69531703,  1.0879776 ,  1.53509474, 47.26639545, 20.40753431,
        32.32945593],
       [ 5.63593631,  1.29986124,  1.49535619, 51.19858365, 18.86273675,
        29.93903164],
       [ 5.92933402,  1.2535304 ,  1.46950402, 48.88956273, 17.75709397,
        33.35825032],
       [ 5.73468363,  1.0106063 ,  1.60736372, 51.31286954, 17.64509841,
        31.04535921],
       [ 5.75655222,  1.09734077,  1.62688153, 52.01376254, 17.92400743,
        30.06277448],
       [ 5.58865531,  1.41678743,  1.56655912, 51.85783908, 19.40134264,
        28.7415254 ],
       [ 5.79859805,  1.15250934,  1.50794812, 48.

In [44]:
pred_cat_df = pd.DataFrame(pred_cat, columns =['Property_A','Property_B','Property_C','Property_D','Property_E','Property_F'])

In [51]:
pred_sum_cat = pred_cat_df.sum(axis='columns')

In [52]:
pred_sum_cat.to_csv('submission5.csv')

In [56]:
pred_sum_cat

0      108.399008
1      107.858603
2      108.208414
3      107.530284
4      108.321775
          ...    
96     108.445015
97     108.312787
98     108.292421
99     108.451621
100    108.400670
Length: 101, dtype: float64

In [69]:
predictions_dt_df = pd.DataFrame(predictions_dt, columns =['Property_A','Property_B','Property_C','Property_D','Property_E','Property_F'])

In [70]:
predictions_sum_dt = predictions_dt_df.sum(axis='columns')

In [71]:
predictions_sum_dt

0      107.162710
1      107.788140
2      107.085052
3      107.788140
4      107.042305
          ...    
96     107.866080
97     107.866080
98     107.057080
99     107.866080
100    111.732760
Length: 101, dtype: float64

In [73]:
predictions_sum_dt.to_csv('submission5.csv')

In [57]:
from sklearn import linear_model

In [58]:
lassoReg = linear_model.Lasso(alpha=0.1)
lassoReg.fit(X_train,Y_train)

Lasso(alpha=0.1)

In [60]:
pred_lasso = lassoReg.predict(X_test)

In [61]:
pred_lasso

array([[ 5.36716413e+00,  2.34397615e+00,  1.12049170e+00,
         2.13540739e+01,  4.23082786e+01,  3.64241961e+01],
       [ 4.71739120e+00,  3.15175121e+00,  9.85499271e-01,
         4.24716070e-01,  5.82251782e+01,  4.15804531e+01],
       [ 4.61548522e+00,  4.69739311e+00,  6.86619211e-01,
        -2.64245391e+01,  7.95827387e+01,  4.70266134e+01],
       [ 5.35296405e+00,  1.76733554e+00,  1.16811683e+00,
         4.10736976e+01,  3.44582475e+01,  2.47708582e+01],
       [ 4.81930238e+00,  1.85676427e+00,  1.39775657e+00,
         3.12048412e+01,  3.51492517e+01,  3.37694992e+01],
       [ 5.07335511e+00,  1.69184008e+00,  1.27928468e+00,
         3.90169789e+01,  2.92156425e+01,  3.19821648e+01],
       [ 5.12997793e+00,  3.28755458e+00,  1.16832507e+00,
         7.52603737e+00,  4.98583901e+01,  4.27675890e+01],
       [ 4.96579987e+00,  3.01942665e+00,  1.10936607e+00,
         6.20852430e+00,  5.46737125e+01,  3.92477446e+01],
       [ 5.03417640e+00,  1.63935391e+00,  1.410

In [62]:
from sklearn.linear_model import RANSACRegressor

In [64]:
reg = RANSACRegressor(random_state=0, min_samples = 200).fit(X_train, Y_train)

In [65]:
reg.score(X_train, Y_train)

0.8375608553525966

In [74]:
pred_ransac = reg.predict(X_test)

In [75]:
predictions_ransac_df = pd.DataFrame(pred_ransac, columns =['Property_A','Property_B','Property_C','Property_D','Property_E','Property_F'])

In [76]:
predictions_ransac_df

Property_A  Property_B  Property_C  Property_D  Property_E  Property_F
0      5.065207    2.543460    1.010235   -6.043850   66.826761   39.189015
1      4.927124    3.632333    1.477244   28.550752   38.957719   32.512414
2      5.533241    1.880212    2.221354   44.334599   48.271460    7.360816
3      6.021393    0.116773    1.202071   17.003301   42.989704   39.994833
4      4.766558    5.880108    0.991304    7.521046   61.474174   31.013264
..          ...         ...         ...         ...         ...         ...
96     7.121847    5.430908    1.010055  -39.289715  109.869512   29.618948
97     6.577303    4.725745    1.066909  -28.320480   94.900374   33.638495
98     4.249289    7.124196    1.266564  -14.704833   72.212445   42.461272
99     5.493348    4.691283    1.743298  -13.745655   90.421619   23.471657
100    6.709208    6.037365    1.156669  -22.970002   83.601663   39.577888

[101 rows x 6 columns]

In [ ]:
'params': {'depth': 2,
  'l2_leaf_reg': 3,
  'iterations': 100,
  'learning_rate': 0.1},

In [ ]:
'params': {'depth': 2,
  'iterations': 100,
  'learning_rate': 0.1,
  'l2_leaf_reg': 0.2},